name: Infra Makefile

on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths: [infrastructure/**, .github/workflows/infrastructure.yml]

jobs:
  pr:
    uses: ./.github/workflows/pr.yml
    strategy:
      matrix:
        repository_name: [infrastructure-modules, infrastructure-live]
    with:
      folder: infrastructure
      file_suffix: "infra"
      repository_name: ${{ matrix.repository_name }}
    secrets: inherit
