name: Infra Docker

on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths:
      [infrastructure-docker/**, .github/workflows/infrastructure-docker.yml]

jobs:
  pr:
    uses: ./.github/workflows/pr.yml
    strategy:
      matrix:
        repository_name: [infrastructure-modules, infrastructure-live]
    with:
      folder: infrastructure-docker
      repository_name: ${{ matrix.repository_name }}
    secrets: inherit
