name: Repository

on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths: [repository/**]

jobs:
  run-backend:
    uses: ./.github/workflows/pr.yml
    strategy:
      matrix:
        repository_name: [
            # infrastructure-modules,
            infrastructure-live,
            # scraper-backend,
            # scraper-frontend,
          ]
    with:
      folder: repository
      file_suffix: "suffff"
      repository_name: ${{ matrix.repository_name }}
    secrets: inherit
