name: Repository

on:
  workflow_dispatch:
  push:
    branches: [trunk]
    paths: [repository/**, .github/workflows/repository.yml]

jobs:
  pr:
    uses: ./.github/workflows/pr.yml
    strategy:
      matrix:
        repository_name:
          [
            infrastructure-live,
            infrastructure-projects,
            infrastructure-modules,
            scraper-backend,
            scraper-frontend,
            VITON-HD,
            tryon-frontend,
          ]
    with:
      folder: repository
      file_suffix: ""
      repository_name: ${{ matrix.repository_name }}
    secrets: inherit
